name: 'Populate planning template'
description: 'Read the planning template and populate with necessary information'
inputs:
  first-responder-schedule-id:
    description: 'The ID of the First Responder Schedule in PagerDuty'
    required: true
  release-coordinator-schedule-id:
    description: 'The ID of the Release Coordinator Schedule in PagerDuty'
    required: true
  filename:
    description: 'Path to the template file'
    required: false
    default: './DISCUSSION_TEMPLATE/discussion.md'
  release-coordinator-placeholder-text:
    description: 'Text to replace the release coordinator name with in the discussion template'
    required: false
    default: 'RELEASE_COORDINATOR_FOR_THE_WEEK'
  first-responder-placeholder-text:
    description: 'Text to replace the first responder name with in the discussion template'
    required: false
    default: 'FIRST_RESPONDER_FOR_THE_WEEK'
  upcoming-release-coordinator-placeholder-text:
    description: 'Text to replace the first responder name with in the discussion template'
    required: false
    default: 'UPCOMING_RELEASE_COORDINATOR_FOR_THE_WEEK'
  upcoming-first-responder-placeholder-text:
    description: 'Text to replace the first responder name with in the discussion template'
    required: false
    default: 'UPCOMING_FIRST_RESPONDER_FOR_THE_WEEK'
outputs:
  templatecontent:
    description: 'The generated template content for the discussion'
runs:
  using: 'node12'
  main: 'dist/index.js'